before_install:
  - gem install bundler # Use the latest version of bundler

script: bundle exec rspec
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
